# Generated by Django 4.1.2 on 2022-12-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cName", models.CharField(max_length=20)),
                ("cSex", models.CharField(default="M", max_length=2)),
                ("cBirthday", models.DateField()),
                ("cEmail", models.EmailField(blank=True, default="", max_length=100)),
                ("cPhone", models.CharField(blank=True, default="", max_length=50)),
                ("cAddr", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
    ]
