# Generated by Django 4.1.2 on 2022-12-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_students"),
    ]

    operations = [
        migrations.DeleteModel(name="students",),
    ]
