# Generated by Django 4.1.2 on 2022-12-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_Price",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_Name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
