# Generated by Django 4.1.2 on 2022-12-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_ordersmodel_productmodel_detailmodel"),
    ]

    operations = [
        migrations.DeleteModel(name="student",),
    ]
