# Generated by Django 4.1.2 on 2022-12-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Headest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(default="", max_length=100)),
                ("pprice", models.IntegerField(default=0)),
                ("pimages", models.CharField(default="", max_length=100)),
                ("pdescription", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="MiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(default="", max_length=100)),
                ("pprice", models.IntegerField(default=0)),
                ("pimages", models.CharField(default="", max_length=100)),
                ("pdescription", models.TextField(blank=True, default="")),
            ],
        ),
    ]
