# Generated by Django 4.1.2 on 2022-12-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_headest_micemodel"),
    ]

    operations = [
        migrations.DeleteModel(name="product",),
    ]
