# Generated by Django 4.1.2 on 2022-12-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_delete_product"),
    ]

    operations = [
        migrations.RenameModel(old_name="Headest", new_name="HeadestModel",),
    ]
